/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ibrahim_Gökdemir;

import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 *
 * @author ieren
 */
public class EmployeeRegistration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public EmployeeRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtsurname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        comboposition = new javax.swing.JComboBox<>();
        btnreturn = new javax.swing.JButton();
        lblphoneerror = new javax.swing.JLabel();
        lblsurnameerror = new javax.swing.JLabel();
        lblnameerror = new javax.swing.JLabel();
        lblpassworderror = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnmale = new javax.swing.JRadioButton();
        btnfemale = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Registration");
        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(java.awt.Color.blue);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Surname*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 99, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 151, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 71, -1));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 111, -1));
        getContentPane().add(txtsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 109, -1));
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 109, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Employee Registiration");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 227, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 139, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Choose password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 106, -1));

        comboposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Staff" }));
        getContentPane().add(comboposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 111, -1));

        btnreturn.setText("Return to login");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 136, -1));

        lblphoneerror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblphoneerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 211, 22));

        lblsurnameerror.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblsurnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 22));

        lblnameerror.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 210, 22));

        lblpassworderror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 197, 20));

        txtadress.setColumns(20);
        txtadress.setRows(5);
        jScrollPane1.setViewportView(txtadress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 90, -1));

        buttonGroup1.add(btnmale);
        btnmale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmale.setForeground(new java.awt.Color(255, 255, 255));
        btnmale.setText("Male");
        getContentPane().add(btnmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 90, -1));

        buttonGroup1.add(btnfemale);
        btnfemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnfemale.setForeground(new java.awt.Color(255, 255, 255));
        btnfemale.setText("Female");
        getContentPane().add(btnfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 80, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mountregister.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Employee newEmployee = new Employee();

        String name = txtname.getText();

        Pattern pattern = Pattern.compile("^[a-zA-ZşŞğĞüÜıIöÖçÇ]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(name);
        boolean matchFound = matcher.find();
        if (!matchFound) {
            lblnameerror.setText("*Name should only contain letters!");
            txtname.setText("");
        }

        String surname = txtsurname.getText();
        Pattern pattern1 = Pattern.compile("^[a-zA-ZşŞğĞüÜıIöÖçÇ]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher1 = pattern1.matcher(surname);
        boolean matchFound1 = matcher1.find();
        if (!matchFound1) {
            lblsurnameerror.setText("*Username should only contain letters!");
            txtsurname.setText("");
        }

        String phone = txtphone.getText();
        Pattern pattern2 = Pattern.compile("^[0-9]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher2 = pattern2.matcher(phone);
        boolean matchFound2 = matcher2.find();
        if (!matchFound2) {
            lblphoneerror.setText("*Phone should only contain numbers!");
            txtphone.setText("");
        }
        String password = txtpassword.getText();
        Pattern pattern3 = Pattern.compile("^[^\\s]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher3 = pattern3.matcher(password);
        boolean matchFound3 = matcher3.find();
        if (!matchFound3) {
            lblpassworderror.setText("*Password cannot be empty!");
            txtpassword.setText("");
            
        }
        if (!btnmale.isSelected() && !btnfemale.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select a gender.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (matchFound && matchFound1 && matchFound2 && matchFound3 && btnmale.isSelected() || btnfemale.isSelected()) {
            newEmployee.name = txtname.getText();
            newEmployee.surname = txtsurname.getText();
            newEmployee.phonenumber = txtphone.getText();
            newEmployee.password = txtpassword.getText();
            newEmployee.address = txtadress.getText();
            newEmployee.Employeetype = comboposition.getSelectedItem().toString();

            String gender = "";
            if (btnmale.isSelected()) {
                gender = "Male";
            } else if (btnfemale.isSelected()) {
                gender = "Female";
            }

            newEmployee.gender = gender;

            String email = txtname.getText().concat(txtsurname.getText()) + "@ercys.com";
            int emailNumber = 1;
            String email1 = email;
            while (DBHelper.isEmailExists(email1)) {
                emailNumber++;
                email1 = txtname.getText().concat(txtsurname.getText()) + "(" + emailNumber + ")" + "@ercys.com";
            }

            newEmployee.email = email1;

            if (DBHelper.InsertNewEmployee(newEmployee)) {
                txtname.setText("");
                txtsurname.setText("");
                txtphone.setText("");
                txtpassword.setText("");
                txtadress.setText("");
                lblnameerror.setText("");
                lblsurnameerror.setText("");
                lblphoneerror.setText("");
                lblpassworderror.setText("");

                JOptionPane.showMessageDialog(this, "\nYour email is: " + newEmployee.email + "", "User inserted.", JOptionPane.INFORMATION_MESSAGE);

            } else {
                //JOptionPane.showMessageDialog(rootPane, "User cannot be inserted");
            }
        }

    }                                           

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Login frmLogin = new Login();
        frmLogin.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistration().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnRegister;
    private javax.swing.JRadioButton btnfemale;
    private javax.swing.JRadioButton btnmale;
    private javax.swing.JButton btnreturn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboposition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblnameerror;
    private javax.swing.JLabel lblpassworderror;
    private javax.swing.JLabel lblphoneerror;
    private javax.swing.JLabel lblsurnameerror;
    private javax.swing.JTextArea txtadress;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsurname;
    // End of variables declaration                   

}
