/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ibrahim_Gökdemir;

/**
 *
 * @author ieren
 */
public class ManagerHome extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public ManagerHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuseeemployees = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuseeassets = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menunewemployees = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menunewasset = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menulogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home page for Manager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 111, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mounthome.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jMenu3.setText("Observe");

        menuseeemployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee.png"))); // NOI18N
        menuseeemployees.setText("See employees");
        menuseeemployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuseeemployeesActionPerformed(evt);
            }
        });
        jMenu3.add(menuseeemployees);
        jMenu3.add(jSeparator1);

        menuseeassets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/financial.png"))); // NOI18N
        menuseeassets.setText("See assets");
        menuseeassets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuseeassetsActionPerformed(evt);
            }
        });
        jMenu3.add(menuseeassets);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Register");

        menunewemployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee.png"))); // NOI18N
        menunewemployees.setText("New employee");
        menunewemployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewemployeesActionPerformed(evt);
            }
        });
        jMenu4.add(menunewemployees);
        jMenu4.add(jSeparator2);

        menunewasset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/financial.png"))); // NOI18N
        menunewasset.setText("New asset");
        menunewasset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewassetActionPerformed(evt);
            }
        });
        jMenu4.add(menunewasset);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Log");

        menulogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        menulogout.setText("Log out");
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menulogout);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void menuseeemployeesActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        SeeEmployees frmseeemployees = new SeeEmployees();
        frmseeemployees.setVisible(true);
        this.dispose();
    }                                                

    private void menunewemployeesActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        EmployeeRegistration frmEmployeeRegistiration = new EmployeeRegistration();
        frmEmployeeRegistiration.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }                                                

    private void menunewassetActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ManagerAssetRegistration frmManagerAssetRegistiration = new ManagerAssetRegistration();
        frmManagerAssetRegistiration.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }                                            

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {                                           
        Login frmlogin = new Login();
        frmlogin.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }                                          

    private void menuseeassetsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        seeassets frmseeassets = new seeassets();
        frmseeassets.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menulogout;
    private javax.swing.JMenuItem menunewasset;
    private javax.swing.JMenuItem menunewemployees;
    private javax.swing.JMenuItem menuseeassets;
    private javax.swing.JMenuItem menuseeemployees;
    // End of variables declaration                   
}
