/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ibrahim_Gökdemir;

import static Ibrahim_Gökdemir.SeeEmployees.connectionString;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.*;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ieren
 */
public class seeassets extends javax.swing.JFrame {

    private void displayData() {
        try {
            Connection conn = DriverManager.getConnection(connectionString);
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM tblmanagerasset";
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 0; i < columnCount; i++) {
                    rowData[i] = rs.getObject(i + 1);
                }
                model.addRow(rowData);
            }

            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void displayData1() {
        try {
            Connection conn = DriverManager.getConnection(connectionString);
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM tblstaffasset";
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 0; i < columnCount; i++) {
                    rowData[i] = rs.getObject(i + 1);
                }
                model.addRow(rowData);
            }

            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Creates new form seemassets
     */
    public seeassets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnshowassets = new javax.swing.JButton();
        bnthome = new javax.swing.JButton();
        btndeletemasset = new javax.swing.JButton();
        btnupdatemasset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnseeassetstaff = new javax.swing.JButton();
        btnhome1 = new javax.swing.JButton();
        btndeletesasset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnshowassetssss = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnreturnhome = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        showemployeesss = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("See Assets");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manager assets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 313, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Serial number", "Acquisition date", "Price", "Category", "Fragility", "Quantity","Manager Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 770, 185));

        btnshowassets.setText("Show assets");
        btnshowassets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowassetsActionPerformed(evt);
            }
        });
        jPanel1.add(btnshowassets, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 170, -1));

        bnthome.setText("Home page");
        bnthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnthomeActionPerformed(evt);
            }
        });
        jPanel1.add(bnthome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));

        btndeletemasset.setText("Delete asset");
        btndeletemasset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletemassetActionPerformed(evt);
            }
        });
        jPanel1.add(btndeletemasset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, -1));

        btnupdatemasset.setText("Update asset");
        btnupdatemasset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatemassetActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdatemasset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mountsee.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 510));

        jTabbedPane4.addTab("Manager assets", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff assets");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 297, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Serial number", "Acquisition date", "Price", "Category", "Fragility", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 721, 187));

        btnseeassetstaff.setText("Show assets");
        btnseeassetstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseeassetstaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnseeassetstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 103, 150, -1));

        btnhome1.setText("Home page");
        btnhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, 153, -1));

        btndeletesasset.setText("Delete asset");
        btndeletesasset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletesassetActionPerformed(evt);
            }
        });
        jPanel2.add(btndeletesasset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        jButton3.setText("Update asset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mountsee.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 510));

        jTabbedPane4.addTab("Staff assets", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(jList1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 82, 181, 226));

        btnshowassetssss.setText("Show assets");
        btnshowassetssss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowassetssssActionPerformed(evt);
            }
        });
        jPanel3.add(btnshowassetssss, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 326, 241, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Assets");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 181, -1));

        btnreturnhome.setText("Home page");
        btnreturnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnhomeActionPerformed(evt);
            }
        });
        jPanel3.add(btnreturnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 241, -1));

        jScrollPane4.setViewportView(jList2);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 180, 230));

        showemployeesss.setText("Show employees");
        showemployeesss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showemployeesssActionPerformed(evt);
            }
        });
        jPanel3.add(showemployeesss, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Employees");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 160, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mountsee.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 510));

        jTabbedPane4.addTab("Show names", jPanel3);

        getContentPane().add(jTabbedPane4);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnshowassetsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        displayData();// TODO add your handling code here:
    }                                             

    private void btnseeassetstaffActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        displayData1();        // TODO add your handling code here:
    }                                                

    private void btnshowassetssssActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:

        DefaultListModel<String> assetNames = new DefaultListModel<>();

        try {
            Connection conn = DriverManager.getConnection(connectionString);
            Statement stmt = conn.createStatement();
            String query = "SELECT name FROM tblmanagerasset UNION SELECT name FROM tblstaffasset ";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String assetName = rs.getString("name");
                assetNames.addElement(assetName);
            }

            conn.close();
            
            if (assetNames.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No assets found!", "No Assets", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jList1.setModel(assetNames);
        }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        jList1.setModel(assetNames);

    }                                                

    private void bnthomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        ManagerHome frmManagerHome = new ManagerHome();
        frmManagerHome.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }                                       

    private void btnhome1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ManagerHome frmManagerHome = new ManagerHome();
        frmManagerHome.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }                                        

    private void btnreturnhomeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        ManagerHome frmManagerHome = new ManagerHome();
        frmManagerHome.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }                                             

    private void showemployeesssActionPerformed(java.awt.event.ActionEvent evt) {                                                
        DefaultListModel<String> employeeNames = new DefaultListModel<>();

        try {
            Connection conn = DriverManager.getConnection(connectionString);
            Statement stmt = conn.createStatement();
            String query = "SELECT Name as name FROM tblregister";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String employeeName = rs.getString("name");
                employeeNames.addElement(employeeName);
            }

            conn.close();
            if (employeeNames.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No employees found!", "No Employees", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jList2.setModel(employeeNames);
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        jList2.setModel(employeeNames);        // TODO add your handling code here:
    }                                               

    private void btndeletemassetActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String mserialno = jTable1.getValueAt(selectedRow, 1).toString();
                Connection conn = DriverManager.getConnection(connectionString);
                Statement stmt = conn.createStatement();

                String deleteQuery = "DELETE FROM tblmanagerasset WHERE serialno = '" + mserialno + "'";
                stmt.executeUpdate(deleteQuery);

                conn.close();

                displayData();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an asset to delete.", "No Asset Selected", JOptionPane.WARNING_MESSAGE);
        }// TODO add your handling code here:
    }                                               

    private void btndeletesassetActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String sserialno = jTable2.getValueAt(selectedRow, 1).toString();
                Connection conn = DriverManager.getConnection(connectionString);
                Statement stmt = conn.createStatement();

                String deleteQuery = "DELETE FROM tblstaffasset WHERE serialno = '" + sserialno + "'";
                stmt.executeUpdate(deleteQuery);

                conn.close();

                displayData1();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an asset to delete.", "No Asset Selected", JOptionPane.WARNING_MESSAGE);
        }  // TODO add your handling code here:
    }                                               

    private void btnupdatemassetActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String name = jTable1.getValueAt(selectedRow, 0).toString();
                String serialNumber = jTable1.getValueAt(selectedRow, 1).toString();
                String acquisitionDate = jTable1.getValueAt(selectedRow, 2).toString();
                String value = jTable1.getValueAt(selectedRow, 3).toString();
                String category = jTable1.getValueAt(selectedRow, 4).toString();
                String fragility = jTable1.getValueAt(selectedRow, 5).toString();
                int quantity = Integer.parseInt(jTable1.getValueAt(selectedRow, 6).toString());
                String managername = jTable1.getValueAt(selectedRow, 7).toString();

                String updatedName = JOptionPane.showInputDialog(this, "Enter updated Name:", name);
                String updatedSerialNumber = JOptionPane.showInputDialog(this, "Enter updated Serial Number:", serialNumber);
                String updatedAcquisitionDate = JOptionPane.showInputDialog(this, "Enter updated Acquisition Date:", acquisitionDate);
                String updatedValue = JOptionPane.showInputDialog(this, "Enter updated Price:", value);
                String updatedmanagername = JOptionPane.showInputDialog(this, "Enter updated manager name:", managername);

                String[] categories = {"Computer equipments", "Furniture", "Vehicles", "Tools"};

                JComboBox<String> categoryComboBox = new JComboBox<>(categories);
                categoryComboBox.setSelectedItem(category);

                JCheckBox fragilityCheckBox = new JCheckBox("Fragile");
                fragilityCheckBox.setSelected(fragility.equals("Fragile"));

                JTextField quantityField = new JTextField(String.valueOf(quantity));
                int result = JOptionPane.showConfirmDialog(this,
                        new Object[]{"Category:", categoryComboBox, "Fragility:", fragilityCheckBox, "Quantity:", quantityField},
                        "Update Category, Fragility, and Quantity", JOptionPane.OK_CANCEL_OPTION);

                if (result == JOptionPane.OK_OPTION) {
                    String updatedCategory = categoryComboBox.getSelectedItem().toString();
                    String updatedFragility = fragilityCheckBox.isSelected() ? "Fragile" : "Not Fragile";
                    int updatedQuantity = Integer.parseInt(quantityField.getText());

                    Connection conn = DriverManager.getConnection(connectionString);
                    Statement stmt = conn.createStatement();

                    String updateQuery = "UPDATE tblmanagerasset SET "
                            + "name = '" + updatedName + "', "
                            + "serialno = '" + updatedSerialNumber + "', "
                            + "acquisitiondate = '" + updatedAcquisitionDate + "', "
                            + "value = '" + updatedValue + "', "
                            + "category = '" + updatedCategory + "', "
                            + "fragile = '" + updatedFragility + "', "
                            + "managername = '" + updatedmanagername + "', "
                            + "mnumber = " + updatedQuantity + " "
                            + "WHERE serialno = '" + serialNumber + "'";

                    stmt.executeUpdate(updateQuery);

                    conn.close();

                    displayData();
                }
            } catch (SQLException | NumberFormatException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an asset to update.", "No Asset Selected", JOptionPane.WARNING_MESSAGE);
        } // TODO add your handling code here:
    }                                               

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow != -1) {
            try {
                String name = jTable2.getValueAt(selectedRow, 0).toString();
                String serialNumber = jTable2.getValueAt(selectedRow, 1).toString();
                String acquisitionDate = jTable2.getValueAt(selectedRow, 2).toString();
                String value = jTable2.getValueAt(selectedRow, 3).toString();
                String category = jTable2.getValueAt(selectedRow, 4).toString();
                String fragility = jTable2.getValueAt(selectedRow, 5).toString();
                int quantity = Integer.parseInt(jTable2.getValueAt(selectedRow, 6).toString());

                String updatedName = JOptionPane.showInputDialog(this, "Enter updated Name:", name);
                String updatedSerialNumber = JOptionPane.showInputDialog(this, "Enter updated Serial Number:", serialNumber);
                String updatedAcquisitionDate = JOptionPane.showInputDialog(this, "Enter updated Acquisition Date:", acquisitionDate);
                String updatedValue = JOptionPane.showInputDialog(this, "Enter updated Price:", value);

                String[] categories = {"Computer equipments", "Furniture", "Vehicles", "Tools"};

                JComboBox<String> categoryComboBox = new JComboBox<>(categories);
                categoryComboBox.setSelectedItem(category);

                JCheckBox fragilityCheckBox = new JCheckBox("Fragile");
                fragilityCheckBox.setSelected(fragility.equals("Fragile"));

                JTextField quantityField = new JTextField(String.valueOf(quantity));
                int result = JOptionPane.showConfirmDialog(this,
                        new Object[]{"Category:", categoryComboBox, "Fragility:", fragilityCheckBox, "Quantity:", quantityField},
                        "Update Category, Fragility, and Quantity", JOptionPane.OK_CANCEL_OPTION);

                if (result == JOptionPane.OK_OPTION) {
                    String updatedCategory = categoryComboBox.getSelectedItem().toString();
                    String updatedFragility = fragilityCheckBox.isSelected() ? "Fragile" : "Not Fragile";
                    int updatedQuantity = Integer.parseInt(quantityField.getText());

                    Connection conn = DriverManager.getConnection(connectionString);
                    Statement stmt = conn.createStatement();

                    String updateQuery = "UPDATE tblstaffasset SET "
                            + "name = '" + updatedName + "', "
                            + "serialno = '" + updatedSerialNumber + "', "
                            + "acquisitiondate = '" + updatedAcquisitionDate + "', "
                            + "value = '" + updatedValue + "', "
                            + "category = '" + updatedCategory + "', "
                            + "fragile = '" + updatedFragility + "', "
                            + "snumber = " + updatedQuantity + " "
                            + "WHERE serialno = '" + serialNumber + "'";

                    stmt.executeUpdate(updateQuery);

                    conn.close();

                    displayData1();
                }
            } catch (SQLException | NumberFormatException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an asset to update.", "No Asset Selected", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seeassets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seeassets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seeassets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seeassets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seeassets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bnthome;
    private javax.swing.JButton btndeletemasset;
    private javax.swing.JButton btndeletesasset;
    private javax.swing.JButton btnhome1;
    private javax.swing.JButton btnreturnhome;
    private javax.swing.JButton btnseeassetstaff;
    private javax.swing.JButton btnshowassets;
    private javax.swing.JButton btnshowassetssss;
    private javax.swing.JButton btnupdatemasset;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton showemployeesss;
    // End of variables declaration                   
}
