/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ibrahim_Gökdemir;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ieren
 */
public class StaffAssetRegistration extends javax.swing.JFrame {

    /**
     *
     *
     *
     * Creates new form AssetRegistiration
     */
    public StaffAssetRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        txtsregister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsserial = new javax.swing.JTextField();
        txtsacquisitiondate = new javax.swing.JTextField();
        txtsvalue = new javax.swing.JTextField();
        cmbscategory = new javax.swing.JComboBox<>();
        sspiner = new javax.swing.JSpinner();
        lblsnameerror = new javax.swing.JLabel();
        lblsserialerror = new javax.swing.JLabel();
        lblsacqerror = new javax.swing.JLabel();
        lblsvalueerror = new javax.swing.JLabel();
        btnstaffhome = new javax.swing.JButton();
        checksfragile = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asset Registration for Staff");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asset registration for staff");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 34, 309, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 217, -1));

        txtsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 107, 181, -1));

        txtsregister.setText("Register");
        txtsregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsregisterActionPerformed(evt);
            }
        });
        getContentPane().add(txtsregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 458, 168, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Serial Number*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 158, 93, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Acquisition date*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 211, 99, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 88, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Category");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 327, 88, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantites");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 99, -1));

        txtsserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsserialActionPerformed(evt);
            }
        });
        getContentPane().add(txtsserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 155, 185, -1));
        getContentPane().add(txtsacquisitiondate, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 208, 186, -1));
        getContentPane().add(txtsvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 262, 185, -1));

        cmbscategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer equipments ", "Furniture", "Vehicles", "Tools" }));
        getContentPane().add(cmbscategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 324, 187, -1));
        getContentPane().add(sspiner, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 126, -1));

        lblsnameerror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblsnameerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 135, 237, 14));

        lblsserialerror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblsserialerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 183, 237, 17));

        lblsacqerror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblsacqerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 236, 237, 20));

        lblsvalueerror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblsvalueerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 296, 237, 16));

        btnstaffhome.setText("Home Page");
        btnstaffhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstaffhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnstaffhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 458, 175, -1));

        checksfragile.setForeground(new java.awt.Color(255, 255, 255));
        checksfragile.setText("Fragile");
        getContentPane().add(checksfragile, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 107, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("dd/mm/yyyy");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mountregister.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtsregisterActionPerformed(java.awt.event.ActionEvent evt) {                                             
        StaffAsset SAsset = new StaffAsset("name", "serialno", "acquisitiondate", "value", "category", "fragile", 123);
        String name = txtsname.getText();

        Pattern pattern = Pattern.compile("^[a-zA-ZşŞğĞüÜıIöÖçÇ\\s]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(name);
        boolean matchFound = matcher.find();
        if (!matchFound) {
            lblsnameerror.setText("*Name should only contain letters!");
            txtsname.setText("");
        }
        String sserial = txtsserial.getText();
        Pattern pattern1 = Pattern.compile("^[0-9]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher1 = pattern1.matcher(sserial);
        boolean matchFound1 = matcher1.find();

        if (!matchFound1) {
            lblsserialerror.setText("*Serial number should only contain numbers!");
            txtsserial.setText("");
        }

        String sacquisitiondate = txtsacquisitiondate.getText();
        Pattern pattern2 = Pattern.compile("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$", Pattern.CASE_INSENSITIVE);
        Matcher matcher2 = pattern2.matcher(sacquisitiondate);
        boolean matchFound2 = matcher2.find();

        if (!matchFound2) {
            lblsacqerror.setText("Please enter a proper date.");
            txtsacquisitiondate.setText("");

        }
        String svalue = txtsvalue.getText();
        Pattern pattern3 = Pattern.compile("^[^\\s]+$", Pattern.CASE_INSENSITIVE);
        Matcher matcher3 = pattern3.matcher(svalue);
        boolean matchFound3 = matcher3.find();

        if (!matchFound3) {
            lblsvalueerror.setText("*Value cannot be empty!");
            txtsvalue.setText("");
        }
        int spinnerValue = Integer.parseInt(sspiner.getValue().toString());
        if (spinnerValue <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Quantity should be greater than 0.");
            return;
        }

        if (matchFound && matchFound1 && matchFound2 && matchFound3 && spinnerValue >= 0) {
            SAsset.name = txtsname.getText();
            SAsset.serialno = txtsserial.getText();
            SAsset.value = txtsvalue.getText();
            SAsset.acquisitiondate = txtsacquisitiondate.getText();
            SAsset.category = cmbscategory.getSelectedItem().toString();
            if (checksfragile.isSelected()) {
                SAsset.fragile = "Fragile";
            } else if (!checksfragile.isSelected()) {
                SAsset.fragile = "Not fragile";
            }
            SAsset.snumber = Integer.parseInt(sspiner.getValue().toString());
            if (DBHelper.InsertNewStaffAsset(SAsset)) {
               
                txtsname.setText("");
                txtsserial.setText("");
                txtsvalue.setText("");
                txtsacquisitiondate.setText("");
                lblsacqerror.setText("");
                lblsnameerror.setText("");
                lblsserialerror.setText("");
                lblsvalueerror.setText("");
                JOptionPane.showMessageDialog(rootPane, "Asset inserted");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Asset cannot be inserted");
            }
        }
        // TODO add your handling code here:
    }                                            

    private void txtsserialActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txtsnameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnstaffhomeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        StaffHome frmStaffHome = new StaffHome();
        frmStaffHome.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffAssetRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffAssetRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffAssetRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffAssetRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffAssetRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnstaffhome;
    private javax.swing.JCheckBox checksfragile;
    private javax.swing.JComboBox<String> cmbscategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblsacqerror;
    private javax.swing.JLabel lblsnameerror;
    private javax.swing.JLabel lblsserialerror;
    private javax.swing.JLabel lblsvalueerror;
    private javax.swing.JSpinner sspiner;
    private javax.swing.JTextField txtsacquisitiondate;
    private javax.swing.JTextField txtsname;
    private javax.swing.JButton txtsregister;
    private javax.swing.JTextField txtsserial;
    private javax.swing.JTextField txtsvalue;
    // End of variables declaration                   
}
